apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-api-secret
type: Opaque
stringData:
  {{ if .Values.services.database.external }}
  DATABASE_URL: {{ .Values.webApi.databaseUrl }}
  DATABASE_READERURL: {{ .Values.webApi.databaseReaderUrl }}
  {{ else }}
  DATABASE_URL: postgres://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Release.Name }}-database-service:5432/{{ .Values.database.name }}
  {{ end }}
  {{ if .Values.services.cache.external }}
  REDIS_URL: {{ .Values.webApi.redisUrl }}
  {{ else }}
  REDIS_URL: redis://{{ .Release.Name }}-cache-service:6379
  {{ end }}
  RSA_PASSPHRASE: {{ .Values.webApi.rsaPassphrase }}
  {{ if .Values.webApi.jwtRsaPublicKey }}
  JWT_RSA_PUBLICKEY: {{ .Values.webApi.jwtRsaPublicKey | quote }}
  {{ end }}
  {{ if .Values.webApi.jwtSecret }}
  JWT_SECRETKEY: {{ .Values.webApi.jwtSecret | quote }}
  {{ end }}
  SMTP_USERNAME: {{ .Values.webApi.email.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.webApi.email.smtp.password | quote }}
  MAILGUN_APIKEY: {{ .Values.webApi.email.mailgun.apiKey | quote }}
  SENDGRID_APIKEY: {{ .Values.webApi.email.sendgrid.apiKey | quote }}
  BUGSNAG_APIKEY: {{ .Values.webApi.bugsnag.apiKey | quote }}
  {{ if .Values.webApi.fly }}
  {{ if .Values.webApi.fly.apiKey }}
  FLY_APIKEY: {{ .Values.webApi.fly.apiKey | quote }}
  {{ end }}
  {{ end }}
  {{ if .Values.webApi.stripe }}
  {{ if .Values.webApi.stripe.secretKey }}
  STRIPE_SECRETKEY: {{ .Values.webApi.stripe.secretKey | quote }}
  {{ end }}
  {{ end }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.webApi.newRelic.licenseKey | quote }}
