{{ if not .Values.services.geoip.external }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-geoip
  labels:
    app: {{ .Release.Name }}-geoip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-geoip
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-geoip
    spec:
      containers:
        - name: geoip
          image: "{{ .Values.services.geoip.image.repository }}:{{ .Values.services.geoip.image.tag }}"
          imagePullPolicy: {{ .Values.services.geoip.image.pullPolicy }}
          ports:
            - containerPort: 8080
      restartPolicy: Always
{{ end }}